name: Dummy Pipeline

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say hello
        run: echo "Hello from dummy pipeline!"

      - name: Run a simple command
        run: |
          echo "This is a dummy GitHub Actions workflow."
          echo "You can add your build/test steps here."

