name: Python Test

on:
  push:
    branches:
      - feature/*
      - main
  pull_request:

jobs:
  Python-Run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check Python
        run: python --version

      - name: test my python script
        run: python test.py
